server:
  port: 8080
  
spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      routes:
      - id: "accounts-ms"
        uri: "lb://ACCOUNTS-MS"
        predicates:
        - Path=/api/v2/acounts/** , /category/**
      - id: "credits-ms"
        uri: "lb://CREDITS-MS"
        predicates:
        - "Path=/api/v2/credits/**"
      - id: "customers-ms"
        uri: "lb://CUSTOMERS-MS"
        predicates:
        - "Path=/api/customers/v2.0.0/**"
                   
      discovery:
        locator:
          enabled: true
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"
  instance:
    instance-id: "${spring.application.name}:${random.uuid}"