#spring:
#  application:
#    name: "accounts-ms"
#  cloud:
#    config:
#      profile: dev
    
#server:
#  port: 0
  
#eureka:
#  instance:
#    instance-id: "${spring.application.name}:${random.uuid}"
