spring:
  application:
    name: "config-server"
  cloud:
    config:
      server:
        git:
          #default-label: main
          default-label: feature/ft-add-github-actions
          uri: "https://github.com/ryusaky/NTTDATA-Microservices.git" #${GITHUB_URL_REPOSITORY}
          search-paths: "config-applications"
          username: "ryusaky" #${GITHUB_USER_NAME} 
          password: "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" #${GITHUB_TOKEN_ACCESS}
          clone-on-start: true
    
server:
  port: 10000
  