spring:
  application:
    name: "config-server"
  cloud:
    config:
      server:
        git:
          default-label: main
          #uri: "https://github.com/ryusaky/config-server.git"
          uri: "https://github.com/ryusaky/NTTDATA-Microservices.git"
          search-paths: "config-applications"
          username: "ryusaky"
          password: "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"
          clone-on-start: true
    
server:
  port: 8888
  