spring:
  application:
    name: "config-server"
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: ${GITHUB_URL_REPOSITORY} #"https://github.com/ryusaky/NTTDATA-Microservices.git"
          search-paths: "config-applications"
          username: ${GITHUB_USER_NAME} #"ryusaky"
          password: ${GITHUB_TOKEN_ACCESS} #"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"
          clone-on-start: true
    
server:
  port: 8888
  