spring:
  application:
    name: "accounts-ms"
    
server:
  port: ${PORT:${SERVER_PORT:0}}
  
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://discovery-service:10001/eureka/'
  instance:
    instance-id: "${spring.application.name}:${random.uuid}"

app:
  versionApp: "v2.0.1"
  testProp: "propertie update with rabbitmq"    

resilience4j:
  circuitbreaker:
    instances:
        backendA:
            registerHealthIndicator: true
            slidingWindowSize: 100
        backendB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 20
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate