spring:
  application:
    name: "accounts-ms"
  data:
    mongodb:
      database: project01
      host: localhost
      port: 27017  
    
server:
  port: ${PORT:${SERVER_PORT:0}}
  
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:10001/eureka/'
  instance:
    instance-id: "${spring.application.name}:${random.uuid}"

app:
  versionMs: "v2.0.1"
  route-account: 
    name: "accounts"
    description: "Service for management of Customers"
  testProp: "propertie update with rabbitmq"  

resilience4j:
  circuitbreaker:
    instances:
        backendA:
            registerHealthIndicator: true
            slidingWindowSize: 100
        backendB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            #recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate
            
            