spring:
  application:
    name: "accounts-ms"
    
server:
  port: 0
  
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.uuid}"

app:
  testProp: "Propiedad de prueba actualizada with rabbitmq"    
