spring:
  application:
    name: "credits-ms"
    
server:
  port: 0
  
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:10001/eureka/'
  instance:
    instance-id: "${spring.application.name}:${random.uuid}"

app:
  versionApp: "v2.0.0"
  testProp: "Propiedad de prueba actualizada for credits with rabbitmq"    
    